import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import { parseAsks } from "./asks.mjs";

export function assemblePrompt(config, arm, askN, runK) {
  const ask = findAsk(config, askN);
  const ballast = readFileSync(config.ballast, "utf8").trim();
  const outputPath = htmlPath(config, arm, askN, runK);
  const segments = [];
  let brand = "";
  let menu = "";
  let instructions = "";

  if (arm === "dump" || arm === "dump-growth") {
    brand = dumpPackage(config.package);
    if (arm === "dump-growth") {
      for (const extra of config.arms["dump-growth"]?.extraPackages ?? []) {
        brand += `\n\n${dumpPackage(extra)}`;
      }
    }
    segments.push(section("Brand fingerprint", brand));
  } else if (arm === "gather") {
    const runId = gatherRunId(askN, runK);
    const [ghostCmd, ...ghostPre] = config.ghostBin.split(/\s+/u);
    menu = execFileSync(
      ghostCmd,
      [
        ...ghostPre,
        ...(config.ghostArgs ?? []),
        "gather",
        firstLine(ask.body),
        "--package",
        config.package,
        "--run",
        runId,
      ],
      { encoding: "utf8" },
    );
    instructions = gatherInstructions(config, askN, runK);
    segments.push(section("Ghost gather menu", menu.trim()));
    segments.push(section("Making-loop instructions", instructions));
  }

  segments.push(section("Ballast", ballast));
  segments.push(section("Ask", ask.body));
  segments.push(`Write a single self-contained HTML file to: ${outputPath}`);
  segments.push(
    "Every prompt ends with: write a single self-contained HTML file to the output path given.",
  );

  const prompt = segments.filter(Boolean).join("\n\n");
  const inventory = inventoryFor({
    ballast,
    brand,
    menu,
    instructions,
    ask: ask.body,
  });
  return { prompt, inventory };
}

export function writePrompt(
  config,
  arm,
  askN,
  runK,
  assembled = assemblePrompt(config, arm, askN, runK),
) {
  const dir = join(config.out, arm, `ask-${askN}`);
  mkdirSync(dir, { recursive: true });
  const promptPath = join(dir, `run-${runK}.prompt.md`);
  const outputPath = join(dir, `run-${runK}.html`);
  writeFileSync(promptPath, assembled.prompt, "utf8");
  writeFileSync(
    join(dir, `run-${runK}.inventory.json`),
    `${JSON.stringify(assembled.inventory, null, 2)}\n`,
    "utf8",
  );
  return { promptPath, outputPath, inventory: assembled.inventory };
}

export function dumpPackage(packageDir) {
  const files = readdirSync(packageDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => entry.name)
    .sort();
  return files
    .map(
      (file) =>
        `# ${basename(file)}\n\n${readFileSync(join(packageDir, file), "utf8").trim()}`,
    )
    .join("\n\n");
}

function findAsk(config, askN) {
  const asks = parseAsks(readFileSync(config.asks, "utf8"));
  const ask = asks.find((item) => item.n === Number(askN));
  if (!ask) throw new Error(`ask ${askN} not found in ${config.asks}`);
  return ask;
}

function gatherInstructions(config, askN, runK) {
  const runId = gatherRunId(askN, runK);
  const dir = join(config.out, "gather", `ask-${askN}`);
  const html = resolve(dir, `run-${runK}.html`);
  const receipt = resolve(dir, `run-${runK}.loop.json`);
  return [
    "You are the host agent. Run the complete Ghost making loop; the harness only supplies this prompt and records the tape.",
    `The menu above was generated by: ${commandPrefix(config)} gather ${quoteArg(firstLine(findAsk(config, askN).body))} --package ${quoteArg(config.package)} --run ${quoteArg(runId)}`,
    "Select only node ids whose described situation applies to the ask, then pull before making:",
    `${commandPrefix(config)} pull <ids> --package ${quoteArg(config.package)} --run ${quoteArg(runId)}`,
    "Inspect pulled materials that govern exactness, structure, or taste. Read files, view images or rendered exemplars when available, and note unavailable material honestly.",
    "Brief the work before writing: Ghost-backed decisions, provisional decisions, materials to use, risks, and no more than five non-negotiables.",
    "If a pulled Skeleton matches the task, start from it first, then fill it with task facts.",
    `Make the single self-contained HTML artifact at ${html}. Screenshots, logs, or notes may be created as evidence; only this run-${runK}.html is scored.`,
    "Render task-relevant viewports, states, and content stress. Verify mechanically and visually: overflow, overlap, dimensions, contrast, focus/order and required content, plus hierarchy, density, rhythm, composition, imagery, and brand fit.",
    "Repair within a bounded budget: default to two repair passes after the first render; use a third pass only for one clear bounded remaining fix.",
    `If checks exist and a diff is available, run ${commandPrefix(config)} review --package ${quoteArg(config.package)} and judge the advisory packet. If rendering or review is unavailable, report the exact gap instead of implying success.`,
    `Write a JSON receipt to ${receipt} with exactly these five top-level fields: {"pulledIds":["node.id"],"inspectedMaterials":["path-or-url"],"rendered":true,"repairPasses":0,"reviewRan":false}.`,
  ].join("\n");
}

function commandPrefix(config) {
  return [config.ghostBin, ...(config.ghostArgs ?? [])].join(" ");
}

function quoteArg(value) {
  const text = String(value);
  return /^[A-Za-z0-9_./:@=-]+$/u.test(text)
    ? text
    : `'${text.replaceAll("'", "'\\''")}'`;
}

function gatherRunId(askN, runK) {
  return `gather-ask${askN}-run${runK}`;
}

function section(title, body) {
  if (!body) return "";
  return `## ${title}\n\n${body}`;
}

function firstLine(body) {
  return (
    body
      .split(/\r?\n/)
      .find((line) => line.trim())
      ?.trim() ?? ""
  );
}

function inventoryFor(parts) {
  const inventory = {
    ballast: countWords(parts.ballast),
    brand: countWords(parts.brand),
    menu: countWords(parts.menu),
    instructions: countWords(parts.instructions),
    ask: countWords(parts.ask),
  };
  inventory.total =
    inventory.ballast +
    inventory.brand +
    inventory.menu +
    inventory.instructions +
    inventory.ask;
  inventory.tokensEstimate = Math.round(inventory.total * 1.33);
  return inventory;
}

function countWords(text) {
  return (text.match(/\S+/gu) ?? []).length;
}

function htmlPath(config, arm, askN, runK) {
  return resolve(config.out, arm, `ask-${askN}`, `run-${runK}.html`);
}
