import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { serializeExpression } from "../expression/writer.js";
import type {
  DesignDecision,
  DesignFingerprint,
  DesignValues,
} from "../types.js";
import { buildTokensCss } from "./tokens-css.js";

export type ContextFormat = "skill" | "prompt" | "bundle";

export interface WriteContextOptions {
  outDir: string;
  format?: ContextFormat;
  /** Override the skill name. Defaults to fingerprint id/slug. */
  name?: string;
}

export interface WriteContextResult {
  outDir: string;
  format: ContextFormat;
  files: string[];
}

export async function writeContextBundle(
  fingerprint: DesignFingerprint,
  options: WriteContextOptions,
): Promise<WriteContextResult> {
  const format = options.format ?? "skill";
  const outDir = options.outDir;
  const name = options.name ?? defaultSkillName(fingerprint);

  await mkdir(outDir, { recursive: true });
  const files: string[] = [];

  if (format === "prompt") {
    const p = join(outDir, "prompt.md");
    await writeFile(p, buildPromptMd(fingerprint, name));
    files.push(p);
    return { outDir, format, files };
  }

  // skill and bundle share SKILL.md + expression.md
  const skillPath = join(outDir, "SKILL.md");
  await writeFile(skillPath, buildSkillMd(fingerprint, name, format));
  files.push(skillPath);

  const exprPath = join(outDir, "expression.md");
  await writeFile(exprPath, serializeExpression(fingerprint));
  files.push(exprPath);

  if (format === "bundle") {
    const cssPath = join(outDir, "tokens.css");
    await writeFile(cssPath, buildTokensCss(fingerprint));
    files.push(cssPath);

    const readmePath = join(outDir, "README.md");
    await writeFile(readmePath, buildReadmeMd(fingerprint, name));
    files.push(readmePath);
  }

  return { outDir, format, files };
}

export function buildSkillMd(
  fingerprint: DesignFingerprint,
  name: string,
  format: ContextFormat,
): string {
  const description = buildSkillDescription(fingerprint, name);
  const includesCss = format === "bundle";
  const fileList = [
    "- `expression.md` — canonical design language (YAML tokens + Character/Signature/Decisions/Values)",
    ...(includesCss
      ? [
          "- `tokens.css` — CSS custom properties derived from expression tokens",
        ]
      : []),
    ...(includesCss ? ["- `README.md` — summary of this bundle"] : []),
  ].join("\n");

  const body = `This skill grounds UI generation in the **${name}** design language.

Read \`expression.md\` first — it is the source of truth. It has four layered sections:

1. **Character** — who this system is (one-paragraph summary)
2. **Signature** — what makes it distinctive (bullet list of traits)
3. **Decisions** — specific design choices with evidence from the source
4. **Values** — hard Do / Don't rules

When generating UI in this language:

- Treat **Values** as non-negotiable gates — never violate a Don't.
- Use **Decisions** as the lookup for specific choices (spacing scale, type ramp, radii).
- Let **Character** and **Signature** shape overall feel, density, and voice.
- Prefer tokens from the YAML frontmatter (palette, spacing, typography, surfaces) over arbitrary values.

## Files

${fileList}
`;

  return `---
name: ${name}
description: ${description}
user-invocable: true
---

${body}`;
}

function buildPromptMd(fingerprint: DesignFingerprint, name: string): string {
  const parts: string[] = [];
  parts.push(
    `You are generating UI in the **${name}** design language. Honor the rules below.`,
  );

  const summary = fingerprint.observation?.summary?.trim();
  if (summary) parts.push(`# Character\n\n${summary}`);

  const traits = fingerprint.observation?.distinctiveTraits ?? [];
  if (traits.length)
    parts.push(`# Signature\n\n${traits.map((t) => `- ${t}`).join("\n")}`);

  const decisions = fingerprint.decisions ?? [];
  if (decisions.length)
    parts.push(`# Decisions\n\n${decisions.map(formatDecision).join("\n\n")}`);

  const values = fingerprint.values;
  if (values && (values.do.length || values.dont.length))
    parts.push(`# Values\n\n${formatValues(values)}`);

  parts.push(`# Tokens\n\n${formatTokens(fingerprint)}`);

  parts.push(
    "# How to use this prompt\n\nWhen asked to build a component or screen, produce HTML that uses the tokens above. Never violate a Don't. Cite the Decision that drove each non-trivial choice.",
  );

  return `${parts.join("\n\n")}\n`;
}

function buildReadmeMd(fingerprint: DesignFingerprint, name: string): string {
  const traits = fingerprint.observation?.distinctiveTraits ?? [];
  const traitsLine = traits.length
    ? ` Signature traits: ${traits.slice(0, 3).join(", ")}.`
    : "";
  return `# ${name} — design context bundle

Generated by \`ghost context\`. Grounding material for AI UI generation in the **${name}** design language.${traitsLine}

## Files

- \`SKILL.md\` — Agent Skill manifest (user-invocable)
- \`expression.md\` — canonical design language (YAML frontmatter + Character/Signature/Decisions/Values)
- \`tokens.css\` — CSS custom properties derived from expression tokens
- \`README.md\` — this file

## Using this bundle

**As a Claude Code / MCP skill:** point the client at this directory. The agent will read \`SKILL.md\` and follow its instructions.

**As context for any LLM:** load \`expression.md\` into the system prompt. For more explicit grounding, concatenate with \`tokens.css\`.

**Feedback loop:** run \`ghost review\` against generated output with this \`expression.md\` as the fingerprint. Drift signals whether the generator honored the system.
`;
}

function buildSkillDescription(
  fingerprint: DesignFingerprint,
  name: string,
): string {
  const traits = fingerprint.observation?.distinctiveTraits ?? [];
  const traitPhrase = traits.length
    ? ` (${traits.slice(0, 3).join(", ")})`
    : "";
  return `Use this skill to generate UI in the ${name} design language${traitPhrase}. Contains the canonical expression, token reference, and Do/Don't rules.`;
}

function defaultSkillName(fingerprint: DesignFingerprint): string {
  const candidate = fingerprint.id || "design-language";
  return candidate
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function formatDecision(d: DesignDecision): string {
  return `## ${d.dimension}\n${d.decision.trim()}`;
}

function formatValues(values: DesignValues): string {
  const doBlock = values.do.length
    ? `## Do\n${values.do.map((v) => `- ${v}`).join("\n")}`
    : "";
  const dontBlock = values.dont.length
    ? `## Don't\n${values.dont.map((v) => `- ${v}`).join("\n")}`
    : "";
  return [doBlock, dontBlock].filter(Boolean).join("\n\n");
}

function formatTokens(fingerprint: DesignFingerprint): string {
  const lines: string[] = [];
  const semantic = fingerprint.palette?.semantic ?? [];
  if (semantic.length) {
    lines.push("**Semantic colors**");
    for (const c of semantic) lines.push(`- \`${c.role}\`: ${c.value}`);
  }
  const spacing = fingerprint.spacing?.scale ?? [];
  if (spacing.length)
    lines.push(`\n**Spacing scale:** ${spacing.join(", ")}px`);
  const sizeRamp = fingerprint.typography?.sizeRamp ?? [];
  if (sizeRamp.length) lines.push(`\n**Type scale:** ${sizeRamp.join(", ")}px`);
  const families = fingerprint.typography?.families ?? [];
  if (families.length)
    lines.push(`\n**Font families:** ${families.join(", ")}`);
  const radii = fingerprint.surfaces?.borderRadii ?? [];
  if (radii.length) lines.push(`\n**Border radii:** ${radii.join(", ")}px`);
  return lines.join("\n");
}
