import type { BudgetLimits, SurveySummaryBudget } from "./summary-types.js";

export const BUDGET_LIMITS: Record<SurveySummaryBudget, BudgetLimits> = {
  compact: {
    valuesPerKind: 6,
    tokens: 20,
    components: 20,
    surfaces: 8,
    arbitraryValues: 6,
    unresolvedValues: 6,
    tokenFamilies: 8,
    tokenAliasDepths: 6,
    themedTokens: 10,
    unresolvedTokens: 6,
    componentSources: 8,
    surfaceGroups: 8,
    groupExamples: 2,
    signalItems: 3,
    resolutionChain: 4,
  },
  standard: {
    valuesPerKind: 12,
    tokens: 40,
    components: 40,
    surfaces: 12,
    arbitraryValues: 12,
    unresolvedValues: 12,
    tokenFamilies: 12,
    tokenAliasDepths: 8,
    themedTokens: 20,
    unresolvedTokens: 12,
    componentSources: 12,
    surfaceGroups: 12,
    groupExamples: 3,
    signalItems: 5,
    resolutionChain: 6,
  },
  full: {
    valuesPerKind: 24,
    tokens: 80,
    components: 80,
    surfaces: 24,
    arbitraryValues: 24,
    unresolvedValues: 24,
    tokenFamilies: 20,
    tokenAliasDepths: 12,
    themedTokens: 40,
    unresolvedTokens: 24,
    componentSources: 20,
    surfaceGroups: 20,
    groupExamples: 4,
    signalItems: 8,
    resolutionChain: 10,
  },
};
