// --- Embedding primitives ---

// --- Decision vocabulary (controlled list for fleet aggregation) ---
export {
  CANONICAL_DECISION_DIMENSIONS,
  type CanonicalDecisionDimension,
  closestCanonical,
  isCanonicalDimension,
  resolveDecisionKind,
} from "./decision-vocabulary.js";
export type { CompareOptions, RoleCandidate } from "./embedding/index.js";
export {
  classifyContrast,
  classifySaturation,
  colorToSemanticColor,
  compareExpressions,
  computeDriftVectors,
  computeEmbedding,
  computeSemanticEmbedding,
  contrastScore,
  DIMENSION_RANGES,
  describeExpression,
  embeddingDistance,
  embedTexts,
  inferSemanticRole,
  parseColorToOklch,
  saturationScore,
} from "./embedding/index.js";
// --- Map (ghost.map/v2) ---
export {
  type GitInfo,
  type InventoryOutput,
  type LanguageHistogramEntry,
  MAP_FILENAME,
  type MapFrontmatter,
  MapFrontmatterSchema,
  REQUIRED_BODY_SECTIONS,
  type RequiredBodySection,
  type TopLevelEntry,
} from "./map/index.js";
// --- Perceptual prior (drift severity calibration) ---
export {
  computeCheckSeverity,
  DEFAULT_MATCH,
  DEFAULT_TOLERANCE,
  escalateForPresence,
  escalateTier,
  PERCEPTUAL_TIER,
  type PerceptualTier,
  resolveMatchShape,
  resolveTolerance,
  TIER_SEVERITY,
  tierForCanonical,
} from "./perceptual-prior.js";
// --- Skill bundle loader ---
export type { SkillBundleFile } from "./skill-bundle-loader.js";
export { loadSkillBundle } from "./skill-bundle-loader.js";
// --- Survey (ghost.survey/v2) ---
export {
  type BreakpointSpec,
  type ColorSpec,
  ColorSpecSchema,
  type ComponentEvidenceSummary,
  type ComponentRow,
  ComponentRowSchema,
  type CountSummary,
  componentRowId,
  formatSurveySummaryMarkdown,
  type LayoutPrimitiveSpec,
  lintSurvey,
  type MotionSpec,
  mergeSurveys,
  type RadiusSpec,
  RECOMMENDED_VALUE_KINDS,
  type RecommendedValueKind,
  type Resolution,
  ResolutionSchema,
  type ResolutionSummary,
  type RowBase,
  recomputeSurveyIds,
  type ScalarUnit,
  type ShadowSpec,
  type SpacingSpec,
  SURVEY_FILENAME,
  type Survey,
  type SurveyComponentsSummary,
  type SurveyLintIssue,
  type SurveyLintReport,
  type SurveyLintSeverity,
  SurveySchema,
  type SurveySource,
  SurveySourceSchema,
  type SurveySourceSummary,
  type SurveySummary,
  type SurveySummaryBudget,
  type SurveySummaryCounts,
  type SurveySummaryOptions,
  type SurveyTokensSummary,
  type SurveyUiSurfacesSummary,
  type SurveyValuesSummary,
  summarizeSurvey,
  type TokenEvidenceSummary,
  type TokenRow,
  TokenRowSchema,
  type TypographySpec,
  tokenRowId,
  type UiSurfaceClassification,
  UiSurfaceClassificationSchema,
  type UiSurfaceDensity,
  type UiSurfaceEvidenceSummary,
  type UiSurfaceGroupSummary,
  type UiSurfaceKind,
  UiSurfaceKindSchema,
  type UiSurfaceLayoutShape,
  type UiSurfaceRenderability,
  UiSurfaceRenderabilitySchema,
  type UiSurfaceRow,
  UiSurfaceRowSchema,
  type UiSurfaceSignals,
  UiSurfaceSignalsSchema,
  type UnknownSpec,
  uiSurfaceRowId,
  type ValueEvidenceSummary,
  type ValueKindSummary,
  type ValueRow,
  ValueRowSchema,
  type ValueSpec,
  ValueSpecSchema,
  valueRowId,
} from "./survey/index.js";
// --- Target resolution ---
export { resolveTarget } from "./target-resolver.js";

// --- Shared types ---
export type {
  Check,
  CheckKind,
  CheckMatchShape,
  ColorRamp,
  ComponentMeta,
  CompositeCluster,
  CompositeComparison,
  CompositeMember,
  CompositePair,
  CSSToken,
  CSSVarsMap,
  DesignDecision,
  DesignObservation,
  DetectedFormat,
  DimensionAck,
  DimensionDelta,
  DimensionStance,
  DivergenceClass,
  DriftSeverity,
  DriftVector,
  DriftVelocity,
  EmbeddingConfig,
  EnrichedComparison,
  EnrichedExpression,
  Expression,
  ExpressionComparison,
  ExpressionHistoryEntry,
  ExpressionReferences,
  ExtractedFile,
  ExtractedMaterial,
  Extractor,
  ExtractorOptions,
  FontDescriptor,
  GhostConfig,
  NormalizedToken,
  Registry,
  RegistryFile,
  RegistryItem,
  RegistryItemType,
  ResolvedRegistry,
  RuleSeverity,
  SampledFile,
  SampledMaterial,
  SemanticColor,
  SourceInfo,
  StructureDrift,
  SyncManifest,
  Target,
  TargetOptions,
  TargetType,
  TemporalComparison,
  TokenCategory,
  TokenFormat,
  ValueDrift,
} from "./types.js";
