// --- Embedding primitives ---

// --- Check (ghost.check/v1) — markdown checks, agent-evaluated ---
export {
  type CheckRelevance,
  GHOST_CHECK_SCHEMA,
  GHOST_CHECK_SEVERITIES,
  type GhostCheckDocument,
  type GhostCheckFrontmatter,
  type GhostCheckLintIssue,
  type GhostCheckLintReport,
  type GhostCheckLintSeverity,
  type GhostCheckMarkdownSeverity,
  lintGhostCheck,
  loadGhostCheck,
  type ParsedCheckMarkdown,
  parseCheckMarkdown,
  type RoutedCheck,
  selectChecksForSurfaces,
} from "./check/index.js";
// --- Fingerprint.yml (ghost.fingerprint/v1) ---
export type {
  GhostFingerprintComposition,
  GhostFingerprintDocument,
  GhostFingerprintEvidence,
  GhostFingerprintExemplar,
  GhostFingerprintExperienceContract,
  GhostFingerprintIntent,
  GhostFingerprintInventory,
  GhostFingerprintInventoryBuildingBlocks,
  GhostFingerprintInventorySource,
  GhostFingerprintInventorySourceKind,
  GhostFingerprintLintIssue,
  GhostFingerprintLintReport,
  GhostFingerprintLintSeverity,
  GhostFingerprintPackageManifest,
  GhostFingerprintPattern,
  GhostFingerprintPatternKind,
  GhostFingerprintPrinciple,
  GhostFingerprintRef,
  GhostFingerprintRefPrefix,
  GhostFingerprintSituation,
  GhostFingerprintSummary,
} from "./fingerprint/index.js";
export {
  GHOST_FINGERPRINT_PACKAGE_SCHEMA,
  GHOST_FINGERPRINT_SCHEMA,
  GHOST_FINGERPRINT_YML_FILENAME,
  GhostFingerprintCompositionSchema,
  GhostFingerprintEvidenceSchema,
  GhostFingerprintExemplarSchema,
  GhostFingerprintExperienceContractSchema,
  GhostFingerprintIntentSchema,
  GhostFingerprintInventoryBuildingBlocksSchema,
  GhostFingerprintInventorySchema,
  GhostFingerprintInventorySourceKindSchema,
  GhostFingerprintInventorySourceSchema,
  GhostFingerprintLayerRefSchema,
  GhostFingerprintPackageManifestSchema,
  GhostFingerprintPatternKindSchema,
  GhostFingerprintPatternSchema,
  GhostFingerprintPrincipleSchema,
  GhostFingerprintRefPrefixSchema,
  GhostFingerprintRefSchema,
  GhostFingerprintSchema,
  GhostFingerprintSituationSchema,
  GhostFingerprintSummarySchema,
  lintGhostFingerprint,
} from "./fingerprint/index.js";
// --- Fingerprint package filenames ---
export {
  FINGERPRINT_COMPOSITION_FILENAME,
  FINGERPRINT_FILENAME,
  FINGERPRINT_INTENT_FILENAME,
  FINGERPRINT_INVENTORY_FILENAME,
  FINGERPRINT_MANIFEST_FILENAME,
  FINGERPRINT_PACKAGE_DIR,
  FINGERPRINT_YML_FILENAME,
  type FingerprintPackagePaths,
  PATTERNS_FILENAME,
  RESOURCES_FILENAME,
} from "./fingerprint-package.js";
// --- Graph (in-memory fingerprint node graph) ---
export {
  type AssembleGraphInput,
  ancestorChain,
  assembleGraph,
  GHOST_GRAPH_ROOT_ID,
  type GhostGraph,
  type GhostGraphNode,
  type GhostGraphNodeOrigin,
  type GraphSlice,
  type GraphSliceNode,
  type GraphSliceProvenance,
  projectFacetsToNodes,
  type ResolveGraphSliceOptions,
  resolveGraphSlice,
} from "./graph/index.js";
// --- Node (ghost.node/v1) — the markdown node artifact ---
export {
  GHOST_NODE_RELATION_KINDS,
  GHOST_NODE_SCHEMA,
  type GhostNodeDocument,
  type GhostNodeFrontmatter,
  GhostNodeFrontmatterSchema,
  type GhostNodeLintIssue,
  type GhostNodeLintReport,
  type GhostNodeLintSeverity,
  type GhostNodeRelation,
  type GhostNodeRelationKind,
  lintGhostNode,
  NodeIdSchema,
  NodeRefSchema,
  type ParseNodeResult,
  parseNode,
  serializeNode,
} from "./node/index.js";
// --- Patterns (ghost.patterns/v1) ---
export type {
  GhostCompositionAnatomy,
  GhostCompositionPattern,
  GhostPatternEvidence,
  GhostPatternsDocument,
  GhostPatternsLintIssue,
  GhostPatternsLintReport,
  GhostPatternsLintSeverity,
  GhostSurfaceTypePattern,
} from "./patterns/index.js";
export {
  GHOST_PATTERNS_FILENAME,
  GHOST_PATTERNS_SCHEMA,
  GhostCompositionAnatomySchema,
  GhostCompositionPatternSchema,
  GhostPatternEvidenceSchema,
  GhostPatternsSchema,
  GhostSurfaceTypePatternSchema,
  lintGhostPatterns,
} from "./patterns/index.js";
// --- Resources (ghost.resources/v1) ---
export type {
  GhostResourceRef,
  GhostResourcesDocument,
  GhostResourcesLintIssue,
  GhostResourcesLintReport,
  GhostResourcesLintSeverity,
  GhostSurfaceResource,
} from "./resources/index.js";
export {
  GHOST_RESOURCES_FILENAME,
  GHOST_RESOURCES_SCHEMA,
  GhostResourceRefSchema,
  GhostResourcesSchema,
  GhostSurfaceResourceSchema,
  lintGhostResources,
} from "./resources/index.js";
// --- Inventory scan output types ---
export type {
  GitInfo,
  InventoryOutput,
  LanguageHistogramEntry,
  TopLevelEntry,
} from "./scan-types.js";
// --- Skill bundle loader ---
export type { SkillBundleFile } from "./skill-bundle-loader.js";
export { loadSkillBundle } from "./skill-bundle-loader.js";
// --- Surfaces (ghost.surfaces/v1) ---
export {
  buildSurfaceMenu,
  GHOST_SURFACE_EDGE_KINDS,
  GHOST_SURFACE_ROOT_ID,
  GHOST_SURFACES_SCHEMA,
  GHOST_SURFACES_YML_FILENAME,
  type GhostSurface,
  type GhostSurfaceEdge,
  type GhostSurfaceEdgeKind,
  type GhostSurfacesDocument,
  type GhostSurfacesLintIssue,
  type GhostSurfacesLintReport,
  type GhostSurfacesLintSeverity,
  GhostSurfacesSchema,
  type GroundingItem,
  groundSurface,
  lintGhostSurfaces,
  type ResolvedSlice,
  resolveSurfaceSlice,
  type SliceNode,
  type SliceProvenance,
  type SurfaceGrounding,
  type SurfaceMenuEntry,
} from "./surfaces/index.js";
// --- Survey (ghost.survey/v1) ---
export {
  type BreakpointSpec,
  type ColorSpec,
  ColorSpecSchema,
  type ComponentEvidenceSummary,
  type ComponentRow,
  ComponentRowSchema,
  type CountSummary,
  catalogSurveyValues,
  componentRowId,
  formatSurveyCatalogMarkdown,
  formatSurveySummaryMarkdown,
  type LayoutPrimitiveSpec,
  lintSurvey,
  type MotionSpec,
  mergeSurveys,
  type RadiusSpec,
  RECOMMENDED_VALUE_KINDS,
  type RecommendedValueKind,
  type Resolution,
  ResolutionSchema,
  type ResolutionSummary,
  type RowBase,
  recomputeSurveyIds,
  type ScalarUnit,
  type ShadowSpec,
  type SpacingSpec,
  SURVEY_FILENAME,
  type Survey,
  type SurveyCatalogCounts,
  type SurveyCatalogKind,
  type SurveyCatalogOptions,
  type SurveyCatalogValue,
  type SurveyComponentsSummary,
  type SurveyLintIssue,
  type SurveyLintReport,
  type SurveyLintSeverity,
  SurveySchema,
  type SurveySource,
  SurveySourceSchema,
  type SurveySourceSummary,
  type SurveySummary,
  type SurveySummaryBudget,
  type SurveySummaryCounts,
  type SurveySummaryOptions,
  type SurveyTokensSummary,
  type SurveyUiSurfacesSummary,
  type SurveyValueCatalog,
  type SurveyValuesSummary,
  summarizeSurvey,
  type TokenEvidenceSummary,
  type TokenRow,
  TokenRowSchema,
  type TypographySpec,
  tokenRowId,
  type UiSurfaceClassification,
  UiSurfaceClassificationSchema,
  type UiSurfaceComposition,
  UiSurfaceCompositionSchema,
  type UiSurfaceDensity,
  type UiSurfaceEvidenceSummary,
  type UiSurfaceGroupSummary,
  type UiSurfaceKind,
  UiSurfaceKindSchema,
  type UiSurfaceLayoutShape,
  type UiSurfaceRenderability,
  UiSurfaceRenderabilitySchema,
  type UiSurfaceRow,
  UiSurfaceRowSchema,
  type UiSurfaceSignals,
  UiSurfaceSignalsSchema,
  type UnknownSpec,
  uiSurfaceRowId,
  type ValueEvidenceSummary,
  type ValueKindSummary,
  type ValueRow,
  ValueRowSchema,
  type ValueSpec,
  ValueSpecSchema,
  valueRowId,
} from "./survey/index.js";
